### ISSUE TITLE
tag release

### ISSUE THREAD

**Issue by roberto-butti** [rozklad/heremaps-flexible-polyline#1]
Hi @rozklad , is there any plan to tag the first release ?
I see on packagist we have only dev-master.

So if you try to install it and you have the min stability as stable, you receive this error:
```
Could not find a version of package rozklad/heremaps-flexible-polyline matching your minimum-stab
  ility (stable). Require it with an explicit version constraint allowing its desired stability.
```

**Comment by rozklad** [comment]
@roberto-butti you are totally right, forgot about it  :cold_sweat: 

Just tagged the current version and it should be available now.

Thank you for bringing it up

**Comment by roberto-butti** [comment]
Welcome to:
```
"rozklad/heremaps-flexible-polyline": "^1.0",
```
in my composer.json ;)
